baseURL = "https://golfstories.netlify.app"
languageCode = "en-us"
title = "Talking Golf"
theme = "ananke"

[params]
site_logo = "/images/logo.png"

[taxonomies]
    tag = "tags"
    category = "categories"

[menu]

  [[menu.main]]
    identifier = "Home"
    name = "Home"
    pre = "<i class='fa fa-heart'></i>"
    url = "/"
    weight = -30

  [[menu.main]]
    name = "Blog"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/categories/blog/"
    weight = -10

  [[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -1